"""Manual cleanup helpers for archived chat transcripts."""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from pnc_automation.app.pnc.domain.chat import normalize_chat_text
from pnc_automation.app.pnc.persistence.archive_ownership import (
    ArchiveOwnershipError,
    chat_scope_from_transcript_path,
    validate_chat_archive_file,
)
from pnc_automation.app.pnc.persistence.chat_archive_state import (
    ChatArchiveSchemaError,
    ChatArchiveState,
    ChatTranscriptEvidence,
    decode_json_object,
    decode_state_document,
    state_bytes,
)
from pnc_automation.core.infra.storage.atomic_file import atomic_write_bytes

_TRANSCRIPT_LINE_PATTERN = re.compile(r"^\[(?P<timestamp>[^\]]+)\]\s+(?P<sender>.+?):\s+(?P<message>.+)$")


@dataclass(frozen=True, slots=True)
class ChatTranscriptCleanupPattern:
    """Describes one normalized message-text pattern that should be removed manually from transcripts."""

    pattern_id: str
    description: str
    message_pattern: re.Pattern[str]


@dataclass(frozen=True, slots=True)
class ParsedChatTranscriptLine:
    """Represents one canonical transcript line parsed into timestamp, sender, and message fields."""

    raw_line: str
    timestamp_text: str
    sender_name: str
    message_text: str


@dataclass(frozen=True, slots=True)
class MatchedChatTranscriptCleanupLine:
    """Carries one transcript line that matched a cleanup pattern."""

    pattern_id: str
    line: ParsedChatTranscriptLine


@dataclass(frozen=True, slots=True)
class ChatTranscriptCleanupResult:
    """Summarizes the deterministic outcome of manually cleaning one transcript text payload."""

    cleaned_text: str
    kept_lines: tuple[str, ...]
    removed_lines: tuple[MatchedChatTranscriptCleanupLine, ...]

    @property
    def changed(self) -> bool:
        """Returns whether the cleanup removed at least one transcript line."""

        return bool(self.removed_lines)


def build_chat_transcript_cleanup_patterns(
    extra_message_regexes: Iterable[str] = (),
) -> tuple[ChatTranscriptCleanupPattern, ...]:
    """Builds the canonical cleanup matchers for known autogenerated transcript rows."""

    patterns = [
        ChatTranscriptCleanupPattern(
            pattern_id="crafted_tap_to_view",
            description="Craft-result broadcast rows ending in Tap to View.",
            message_pattern=re.compile(r"^i crafted\b.+\(\s*tap to view\s*\)$", re.IGNORECASE),
        ),
        ChatTranscriptCleanupPattern(
            pattern_id="legendary_hero_timed_recruit",
            description="Timed Recruit legendary-hero obtain broadcasts ending in Tap to Join.",
            message_pattern=re.compile(
                r"^i obtained legendary hero\b.+\btimed recruit\b.+\(\s*tap to join\s*\)$",
                re.IGNORECASE,
            ),
        ),
        ChatTranscriptCleanupPattern(
            pattern_id="maze_treasure_loot",
            description="Maze Treasure loot broadcasts ending in Tap to View.",
            message_pattern=re.compile(r"^i got\b.+\bmaze treasure\b.+\(\s*tap to view\s*\)$", re.IGNORECASE),
        ),
    ]
    for index, expression in enumerate(extra_message_regexes, start=1):
        patterns.append(
            ChatTranscriptCleanupPattern(
                pattern_id=f"extra_message_regex_{index}",
                description="User-supplied transcript cleanup regex.",
                message_pattern=re.compile(expression, re.IGNORECASE),
            )
        )
    return tuple(patterns)


def clean_chat_transcript_text(
    transcript_text: str,
    *,
    patterns: tuple[ChatTranscriptCleanupPattern, ...] | None = None,
) -> ChatTranscriptCleanupResult:
    """Removes transcript lines whose normalized message text matches one cleanup pattern."""

    active_patterns = build_chat_transcript_cleanup_patterns() if patterns is None else patterns
    kept_lines: list[str] = []
    removed_lines: list[MatchedChatTranscriptCleanupLine] = []
    trailing_newline = transcript_text.endswith("\n")
    for raw_line in transcript_text.splitlines():
        if raw_line == "":
            kept_lines.append(raw_line)
            continue
        parsed_line = parse_chat_transcript_line(raw_line)
        pattern = match_chat_transcript_cleanup_pattern(parsed_line.message_text, patterns=active_patterns)
        if pattern is None:
            kept_lines.append(raw_line)
            continue
        removed_lines.append(MatchedChatTranscriptCleanupLine(pattern_id=pattern.pattern_id, line=parsed_line))
    cleaned_text = "\n".join(kept_lines)
    if trailing_newline and cleaned_text != "":
        cleaned_text += "\n"
    return ChatTranscriptCleanupResult(
        cleaned_text=cleaned_text,
        kept_lines=tuple(kept_lines),
        removed_lines=tuple(removed_lines),
    )


def parse_chat_transcript_line(raw_line: str) -> ParsedChatTranscriptLine:
    """Parses one transcript line or fails fast when the line does not match the canonical archive format."""

    match = _TRANSCRIPT_LINE_PATTERN.match(raw_line)
    if match is None:
        raise ValueError(f"Malformed transcript line: {raw_line!r}")
    timestamp_text = match.group("timestamp").strip()
    sender_name = match.group("sender").strip()
    message_text = match.group("message").strip()
    if timestamp_text == "" or sender_name == "" or message_text == "":
        raise ValueError(f"Malformed transcript line: {raw_line!r}")
    return ParsedChatTranscriptLine(
        raw_line=raw_line,
        timestamp_text=timestamp_text,
        sender_name=sender_name,
        message_text=message_text,
    )


def match_chat_transcript_cleanup_pattern(
    message_text: str,
    *,
    patterns: tuple[ChatTranscriptCleanupPattern, ...],
) -> ChatTranscriptCleanupPattern | None:
    """Returns the first cleanup matcher that recognizes one normalized transcript message text."""

    normalized_message = normalize_chat_text(message_text)
    for pattern in patterns:
        if pattern.message_pattern.match(normalized_message):
            return pattern
    return None


def persist_cleaned_chat_transcript(path: Path, cleaned_text: str) -> None:
    """Publishes an intentional cleanup edit under the chat stream ownership boundary."""

    try:
        scope = chat_scope_from_transcript_path(path)
    except ArchiveOwnershipError as error:
        raise ValueError(str(error)) from error
    with scope.lock():
        if scope.pending_path.exists():
            raise RuntimeError("Chat transcript cleanup is blocked while pending archive recovery exists.")
        if not path.is_file():
            raise ValueError(f"Chat transcript cleanup target is not a regular file: {path}")
        original_bytes = path.read_bytes()
        _validate_state_against_transcript(scope.root, path, original_bytes)
        atomic_write_bytes(path.absolute(), cleaned_text.encode("utf-8"), prefix="cleanup-", suffix=".tmp")
        _update_state_transcript_evidence(scope.root, path, cleaned_text.encode("utf-8"))


def clean_and_persist_chat_transcript(
    path: Path,
    *,
    patterns: tuple[ChatTranscriptCleanupPattern, ...],
) -> ChatTranscriptCleanupResult:
    """Reads, cleans, and publishes one transcript while holding its stream lock."""

    try:
        scope = chat_scope_from_transcript_path(path)
    except ArchiveOwnershipError as error:
        raise ValueError(str(error)) from error
    with scope.lock():
        if scope.pending_path.exists():
            raise RuntimeError("Chat transcript cleanup is blocked while pending archive recovery exists.")
        try:
            original_text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError) as error:
            raise ValueError(f"Unable to read chat transcript for cleanup: {path}") from error
        result = clean_chat_transcript_text(original_text, patterns=patterns)
        if result.changed:
            cleaned_bytes = result.cleaned_text.encode("utf-8")
            _validate_state_against_transcript(scope.root, path, original_text.encode("utf-8"))
            atomic_write_bytes(path.absolute(), cleaned_bytes, prefix="cleanup-", suffix=".tmp")
            _update_state_transcript_evidence(scope.root, path, cleaned_bytes)
        return result


def _validate_state_against_transcript(root: Path, transcript_path: Path, transcript_bytes: bytes) -> None:
    """Rejects cleanup when the state evidence no longer matches the bytes being edited."""

    state_path = transcript_path.parent / "state.json"
    try:
        validate_chat_archive_file(root, state_path, allowed_names={"state.json"}, allow_missing=True)
    except ArchiveOwnershipError as error:
        raise ValueError("Chat cleanup state path is not safe.") from error
    if not state_path.exists():
        return
    try:
        decoded = decode_state_document(decode_json_object(state_path.read_bytes(), field_name="state"), allow_legacy=True)
    except (OSError, ChatArchiveSchemaError) as error:
        raise RuntimeError("Chat cleanup is blocked by malformed archive state.") from error
    evidence = decoded.state.transcript_evidence
    if not decoded.legacy and evidence is None:
        raise RuntimeError("Chat cleanup is blocked because state declares no target-day transcript.")
    if evidence is not None and (
        evidence.length != len(transcript_bytes) or evidence.sha256 != hashlib.sha256(transcript_bytes).hexdigest()
    ):
        raise RuntimeError("Chat cleanup is blocked because transcript bytes do not match state evidence.")


def _update_state_transcript_evidence(root: Path, transcript_path: Path, transcript_bytes: bytes) -> None:
    """Updates the same-day state evidence after an intentional transcript edit."""

    state_path = transcript_path.parent / "state.json"
    if not state_path.exists():
        return
    try:
        decoded = decode_state_document(decode_json_object(state_path.read_bytes(), field_name="state"), allow_legacy=True)
        updated = ChatArchiveState(
            snapshot=decoded.state.snapshot,
            last_captured_at=decoded.state.last_captured_at,
            gap_detected=decoded.state.gap_detected,
            transcript_evidence=ChatTranscriptEvidence(
                exists=True,
                length=len(transcript_bytes),
                sha256=hashlib.sha256(transcript_bytes).hexdigest(),
            ),
        )
        validate_chat_archive_file(root, state_path, allowed_names={"state.json"}, allow_missing=False)
        atomic_write_bytes(state_path.absolute(), state_bytes(updated), prefix="cleanup-state-", suffix=".tmp")
    except (OSError, ChatArchiveSchemaError, ArchiveOwnershipError) as error:
        raise RuntimeError("Chat cleanup transcript was published but its state evidence could not be updated.") from error
