"""Canonical semantic OCR families, gated by independently accepted identity."""

from __future__ import annotations

from pnc_automation.app.pnc.enums.screen_type import ScreenType


_SCREEN_FAMILIES = frozenset({
    ScreenType.ANDROID_HOME,
    ScreenType.PNC_LOGIN,
    ScreenType.PNC_ACCOUNT_SWITCH,
    ScreenType.PNC_LORD_INFO,
    ScreenType.PNC_PLAYER_TERRITORY,
    ScreenType.PNC_PLAYER_PROFILE,
    ScreenType.PNC_VIP,
    ScreenType.PNC_VIP_DAILY_RESET,
    ScreenType.PNC_IMPROVE_MIGHT,
    ScreenType.PNC_EVENT_CENTER,
    ScreenType.PNC_GIFT_CENTER,
    ScreenType.PNC_WORLD_MAP,
    ScreenType.PNC_WORLD_COORDINATE_DIALOG,
    ScreenType.PNC_WORLD_MAP_OVERVIEW,
    ScreenType.PNC_WORLD_KINGDOM_LIST,
    ScreenType.PNC_MAIL_HUB,
    ScreenType.PNC_MAILBOX_LIST,
    ScreenType.PNC_MAIL_THREAD,
    ScreenType.PNC_MAIL_COMPOSE_POPUP,
    ScreenType.PNC_ALLIANCE_HOME,
    ScreenType.PNC_MORE_MENU,
    ScreenType.PNC_SETTINGS,
    ScreenType.PNC_BUILDING_DETAILS,
    ScreenType.PNC_BUILD_SPEEDUP,
    ScreenType.PNC_BUILD_SPEEDUP_CONFIRM,
    ScreenType.PNC_CASTLE,
    ScreenType.PNC_TERRITORY_OVERVIEW,
    ScreenType.PNC_HALL_OF_WAR,
    ScreenType.PNC_SACRED_TREE,
    ScreenType.PNC_SACRED_TREE_BLESSING_RECORD,
    ScreenType.PNC_OTHER_LORD_SACRED_TREE,
    ScreenType.PNC_PIT,
    ScreenType.PNC_RARE_EARTH_FIELD,
    ScreenType.PNC_DISPATCH,
    ScreenType.PNC_SANCTUM,
    ScreenType.PNC_RELICS,
    ScreenType.PNC_TOWER_OF_TRIAL,
    ScreenType.PNC_TRIAL_CHALLENGE,
    ScreenType.PNC_TRIAL_APPLICABLE_STATS,
    ScreenType.PNC_GODDESS_STATUE,
    ScreenType.PNC_BUILD_MENU_FIXED_SLOT,
    ScreenType.PNC_BUILD_MENU_LARGE_SLOT,
    ScreenType.PNC_BUILD_MENU_SMALL_SLOT,
    ScreenType.PNC_BUILDING_CONSTRUCTION,
    ScreenType.PNC_INSTITUTE,
    ScreenType.PNC_WAREHOUSE,
    ScreenType.PNC_TRAP_WORKSHOP,
    ScreenType.PNC_TRAP_WORKSHOP_EFFECT_TABLE,
    ScreenType.PNC_HERO_HALL,
    ScreenType.PNC_WATCHTOWER,
    ScreenType.PNC_BLACKSMITH,
    ScreenType.PNC_GEAR,
    ScreenType.PNC_GEM,
    ScreenType.PNC_SAURGEM,
    ScreenType.PNC_WARSIGIL,
    ScreenType.PNC_HERO_CURIO,
    ScreenType.PNC_ASCEND,
    ScreenType.PNC_ALLIANCE_HALL,
    ScreenType.PNC_MARKET,
    ScreenType.PNC_ALLIANCE_MEMBER_REINFORCE,
    ScreenType.PNC_ALLIANCE_MEMBER_TRANSPORT,
    ScreenType.PNC_INFANTRY_BARRACKS,
    ScreenType.PNC_CAVALRY_BARRACKS,
    ScreenType.PNC_RANGED_BARRACKS,
    ScreenType.PNC_SIEGE_FACTORY,
    ScreenType.PNC_BARRACKS_UNLOCK_TABLE,
    ScreenType.PNC_SAUROI_LAIR,
    ScreenType.PNC_SAUREGG,
    ScreenType.PNC_WALL,
    ScreenType.PNC_DEFENSE_INFO,
    ScreenType.PNC_HOME_CITY,
    ScreenType.PNC_BUILD_QUEUE,
    ScreenType.PNC_POPUP,
    ScreenType.PNC_BAG,
    ScreenType.PNC_QUEST_MAIN,
    ScreenType.PNC_QUEST_DAILY,
    ScreenType.PNC_ALLIANCE_JOIN,
    ScreenType.PNC_CHAT,
    ScreenType.PNC_CHAT_PLAYER_ACTION_POPUP,
    ScreenType.PNC_ALLIANCE_MEMBER_LIST,
    ScreenType.PNC_ALLIANCE_MEMBER_MANAGE_POPUP,
    ScreenType.PNC_DAILY_TO_DO,
    ScreenType.PNC_MIGHT_RANK,
    ScreenType.PNC_RESEARCH_TREE,
    ScreenType.PNC_RESEARCH_QUEUE,
    ScreenType.PNC_CASTLE_SELECTION,
    ScreenType.PNC_CAMPAIGN_MAP,
    ScreenType.PNC_CAMPAIGN_CHAPTER,
    ScreenType.PNC_CAMPAIGN_STAGE,
    ScreenType.PNC_VERSUS_CENTER,
    ScreenType.PNC_HERO_SHOWDOWN_ELEMENTAL_INTRO,
    ScreenType.PNC_HERO_FORMATION,
    ScreenType.PNC_HERO_SHOWDOWN_RANKING,
})


def runtime_screen_family_ocr_types() -> frozenset[ScreenType]:
    """Return the families with concrete semantic parsers in the runtime."""

    return _SCREEN_FAMILIES


def can_attempt_screen_family_ocr(*, request_screen: ScreenType, observed_screen: ScreenType) -> bool:
    """Allow content only for its exact, independently accepted screen family."""

    return request_screen in _SCREEN_FAMILIES and observed_screen == request_screen
