"""Regression coverage for the manual chat-transcript cleanup helper."""

from __future__ import annotations

import unittest
import tempfile
from pathlib import Path

from pnc_automation.app.pnc.persistence.chat_transcript_cleanup import (
    build_chat_transcript_cleanup_patterns,
    clean_chat_transcript_text,
    persist_cleaned_chat_transcript,
)
from pnc_automation.app.pnc.persistence.archive_ownership import chat_scope_from_transcript_path


class ChatTranscriptCleanupTests(unittest.TestCase):
    """Validates the manual transcript cleaner for known autogenerated row families."""

    def test_clean_chat_transcript_text_removes_known_autogenerated_rows(self) -> None:
        """Removes the built-in craft, legendary-hero, and maze-treasure broadcast families."""

        transcript = (
            "[2026-03-24T10:00:00Z] K315c29a481282: I got [Lost Curio Box] x1 in Maze Treasure! (Tap to View)\n"
            "[2026-03-24T10:01:00Z] Narzisse d21: I crafted 5-star Mythic Hell Blade! (Tap to view)\n"
            "[2026-03-24T10:02:00Z] Enemy Bob: Hello there\n"
            "[2026-03-24T10:03:00Z] K3153fd21f5324: I obtained legendary hero [Jumong] in Timed Recruit event! (Tap to Join)\n"
        )

        result = clean_chat_transcript_text(transcript)

        self.assertTrue(result.changed)
        self.assertEqual(len(result.removed_lines), 3)
        self.assertEqual(result.cleaned_text, "[2026-03-24T10:02:00Z] Enemy Bob: Hello there\n")

    def test_clean_chat_transcript_text_keeps_normal_player_rows(self) -> None:
        """Keeps normal player chat even when it happens to mention one cleanup verb."""

        transcript = (
            "[2026-03-24T10:00:00Z] [Ruler] Alice: I crafted this rally comp yesterday\n"
            "[2026-03-24T10:01:00Z] Enemy Bob: I got lucky in chat today\n"
        )

        result = clean_chat_transcript_text(transcript)

        self.assertFalse(result.changed)
        self.assertEqual(result.cleaned_text, transcript)

    def test_clean_chat_transcript_text_supports_extra_regexes(self) -> None:
        """Allows one manual run to extend the built-in cleanup set with extra message regexes."""

        transcript = "[2026-03-24T10:00:00Z] Enemy Bob: Hello there\n"
        patterns = build_chat_transcript_cleanup_patterns((r"^hello there$",))

        result = clean_chat_transcript_text(transcript, patterns=patterns)

        self.assertTrue(result.changed)
        self.assertEqual(len(result.removed_lines), 1)
        self.assertEqual(result.removed_lines[0].pattern_id, "extra_message_regex_1")
        self.assertEqual(result.cleaned_text, "")

    def test_clean_chat_transcript_text_fails_on_malformed_non_empty_lines(self) -> None:
        """Fails fast when a transcript contains a non-empty line outside the canonical archive format."""

        with self.assertRaisesRegex(ValueError, "Malformed transcript line"):
            clean_chat_transcript_text("Enemy Bob says hello\n")

    def test_persisted_cleanup_uses_canonical_lock_and_atomic_publication(self) -> None:
        """Managed cleanup edits are serialized and replace the transcript through a sibling temp file."""

        with tempfile.TemporaryDirectory() as temporary_directory:
            transcript = Path(temporary_directory) / "2026-03-24" / "account" / "k1_castle" / "kingdom" / "transcript.log"
            transcript.parent.mkdir(parents=True)
            transcript.write_text("[2026-03-24T10:00:00Z] Enemy Bob: Hello\n", encoding="utf-8")
            persist_cleaned_chat_transcript(transcript, "[2026-03-24T10:00:00Z] Enemy Bob: Changed\n")
            self.assertEqual("[2026-03-24T10:00:00Z] Enemy Bob: Changed\n", transcript.read_text(encoding="utf-8"))

    def test_persisted_cleanup_refuses_pending_recovery(self) -> None:
        """Manual edits cannot destroy evidence owned by a pending chat transaction."""

        with tempfile.TemporaryDirectory() as temporary_directory:
            transcript = Path(temporary_directory) / "2026-03-24" / "account" / "k1_castle" / "kingdom" / "transcript.log"
            transcript.parent.mkdir(parents=True)
            original = "[2026-03-24T10:00:00Z] Enemy Bob: Hello\n"
            transcript.write_text(original, encoding="utf-8")
            scope = chat_scope_from_transcript_path(transcript)
            scope.pending_path.write_text("{}", encoding="utf-8")
            with self.assertRaisesRegex(RuntimeError, "pending archive recovery"):
                persist_cleaned_chat_transcript(transcript, "")
            self.assertEqual(original, transcript.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
