"""Manual cleanup helpers for archived chat transcripts."""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Iterable

from pnc_automation.pnc.chat import normalize_chat_text

_TRANSCRIPT_LINE_PATTERN = re.compile(r"^\[(?P<timestamp>[^\]]+)\]\s+(?P<sender>.+?):\s+(?P<message>.+)$")


@dataclass(frozen=True, slots=True)
class ChatTranscriptCleanupPattern:
    """Describes one normalized message-text pattern that should be removed manually from transcripts."""

    pattern_id: str
    description: str
    message_pattern: re.Pattern[str]


@dataclass(frozen=True, slots=True)
class ParsedChatTranscriptLine:
    """Represents one canonical transcript line parsed into timestamp, sender, and message fields."""

    raw_line: str
    timestamp_text: str
    sender_name: str
    message_text: str


@dataclass(frozen=True, slots=True)
class MatchedChatTranscriptCleanupLine:
    """Carries one transcript line that matched a cleanup pattern."""

    pattern_id: str
    line: ParsedChatTranscriptLine


@dataclass(frozen=True, slots=True)
class ChatTranscriptCleanupResult:
    """Summarizes the deterministic outcome of manually cleaning one transcript text payload."""

    cleaned_text: str
    kept_lines: tuple[str, ...]
    removed_lines: tuple[MatchedChatTranscriptCleanupLine, ...]

    @property
    def changed(self) -> bool:
        """Returns whether the cleanup removed at least one transcript line."""

        return bool(self.removed_lines)


def build_chat_transcript_cleanup_patterns(
    extra_message_regexes: Iterable[str] = (),
) -> tuple[ChatTranscriptCleanupPattern, ...]:
    """Builds the canonical cleanup matchers for known autogenerated transcript rows."""

    patterns = [
        ChatTranscriptCleanupPattern(
            pattern_id="crafted_tap_to_view",
            description="Craft-result broadcast rows ending in Tap to View.",
            message_pattern=re.compile(r"^i crafted\b.+\(\s*tap to view\s*\)$", re.IGNORECASE),
        ),
        ChatTranscriptCleanupPattern(
            pattern_id="legendary_hero_timed_recruit",
            description="Timed Recruit legendary-hero obtain broadcasts ending in Tap to Join.",
            message_pattern=re.compile(
                r"^i obtained legendary hero\b.+\btimed recruit\b.+\(\s*tap to join\s*\)$",
                re.IGNORECASE,
            ),
        ),
        ChatTranscriptCleanupPattern(
            pattern_id="maze_treasure_loot",
            description="Maze Treasure loot broadcasts ending in Tap to View.",
            message_pattern=re.compile(r"^i got\b.+\bmaze treasure\b.+\(\s*tap to view\s*\)$", re.IGNORECASE),
        ),
    ]
    for index, expression in enumerate(extra_message_regexes, start=1):
        patterns.append(
            ChatTranscriptCleanupPattern(
                pattern_id=f"extra_message_regex_{index}",
                description="User-supplied transcript cleanup regex.",
                message_pattern=re.compile(expression, re.IGNORECASE),
            )
        )
    return tuple(patterns)


def clean_chat_transcript_text(
    transcript_text: str,
    *,
    patterns: tuple[ChatTranscriptCleanupPattern, ...] | None = None,
) -> ChatTranscriptCleanupResult:
    """Removes transcript lines whose normalized message text matches one cleanup pattern."""

    active_patterns = build_chat_transcript_cleanup_patterns() if patterns is None else patterns
    kept_lines: list[str] = []
    removed_lines: list[MatchedChatTranscriptCleanupLine] = []
    trailing_newline = transcript_text.endswith("\n")
    for raw_line in transcript_text.splitlines():
        if raw_line == "":
            kept_lines.append(raw_line)
            continue
        parsed_line = parse_chat_transcript_line(raw_line)
        pattern = match_chat_transcript_cleanup_pattern(parsed_line.message_text, patterns=active_patterns)
        if pattern is None:
            kept_lines.append(raw_line)
            continue
        removed_lines.append(MatchedChatTranscriptCleanupLine(pattern_id=pattern.pattern_id, line=parsed_line))
    cleaned_text = "\n".join(kept_lines)
    if trailing_newline and cleaned_text != "":
        cleaned_text += "\n"
    return ChatTranscriptCleanupResult(
        cleaned_text=cleaned_text,
        kept_lines=tuple(kept_lines),
        removed_lines=tuple(removed_lines),
    )


def parse_chat_transcript_line(raw_line: str) -> ParsedChatTranscriptLine:
    """Parses one transcript line or fails fast when the line does not match the canonical archive format."""

    match = _TRANSCRIPT_LINE_PATTERN.match(raw_line)
    if match is None:
        raise ValueError(f"Malformed transcript line: {raw_line!r}")
    timestamp_text = match.group("timestamp").strip()
    sender_name = match.group("sender").strip()
    message_text = match.group("message").strip()
    if timestamp_text == "" or sender_name == "" or message_text == "":
        raise ValueError(f"Malformed transcript line: {raw_line!r}")
    return ParsedChatTranscriptLine(
        raw_line=raw_line,
        timestamp_text=timestamp_text,
        sender_name=sender_name,
        message_text=message_text,
    )


def match_chat_transcript_cleanup_pattern(
    message_text: str,
    *,
    patterns: tuple[ChatTranscriptCleanupPattern, ...],
) -> ChatTranscriptCleanupPattern | None:
    """Returns the first cleanup matcher that recognizes one normalized transcript message text."""

    normalized_message = normalize_chat_text(message_text)
    for pattern in patterns:
        if pattern.message_pattern.match(normalized_message):
            return pattern
    return None
