pnc_accounts:
- pnc_account_id: m3x3mayo@gmail.com
  castles:
  - kingdom: K314
    castle_name: K314e66ab29777
    castle_level: 4
  - kingdom: K304
    castle_name: K304554ca2797
    castle_level: 5
