"""Manually removes selected autogenerated rows from archived chat transcripts."""

from __future__ import annotations

import argparse
from pathlib import Path

from _script_bootstrap import ensure_repo_root_on_path

root = ensure_repo_root_on_path()

from pnc_automation.app.pnc.persistence.chat_transcript_cleanup import (
    build_chat_transcript_cleanup_patterns,
    clean_chat_transcript_text,
)


def main() -> int:
    """Parses arguments, previews or writes transcript cleanup changes, and prints a summary."""

    parser = argparse.ArgumentParser(description="Preview or remove selected autogenerated rows from archived chat transcripts.")
    parser.add_argument(
        "paths",
        nargs="+",
        help="Transcript file paths or directories to scan recursively for transcript.log files.",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Rewrite matching transcript files in place. Defaults to dry-run preview mode.",
    )
    parser.add_argument(
        "--show-removed",
        action="store_true",
        help="Print each removed transcript line in addition to the per-file summary.",
    )
    parser.add_argument(
        "--extra-message-regex",
        action="append",
        default=[],
        help="Additional case-insensitive regex matched against normalized message text. May be provided multiple times.",
    )
    arguments = parser.parse_args()

    transcript_paths = _discover_transcript_paths(arguments.paths)
    patterns = build_chat_transcript_cleanup_patterns(arguments.extra_message_regex)
    changed_files = 0
    removed_lines = 0
    for transcript_path in transcript_paths:
        original_text = transcript_path.read_text(encoding="utf-8")
        result = clean_chat_transcript_text(original_text, patterns=patterns)
        if result.changed:
            changed_files += 1
            removed_lines += len(result.removed_lines)
            if arguments.write:
                with transcript_path.open("w", encoding="utf-8", newline="\n") as handle:
                    handle.write(result.cleaned_text)
        print(f"{transcript_path} removed={len(result.removed_lines)} mode={'write' if arguments.write else 'dry-run'}")
        if not arguments.show_removed:
            continue
        for removed in result.removed_lines:
            print(
                f"  {removed.pattern_id}: [{removed.line.timestamp_text}] {removed.line.sender_name}: {removed.line.message_text}"
            )
    print(
        f"processed_files={len(transcript_paths)} changed_files={changed_files} removed_lines={removed_lines} "
        f"mode={'write' if arguments.write else 'dry-run'}"
    )
    return 0


def _discover_transcript_paths(raw_paths: list[str]) -> tuple[Path, ...]:
    """Resolves the requested transcript files and directory scans into one deterministic file list."""

    transcript_paths: list[Path] = []
    for raw_path in raw_paths:
        path = Path(raw_path).resolve()
        if path.is_file():
            transcript_paths.append(path)
            continue
        if path.is_dir():
            transcript_paths.extend(sorted(item.resolve() for item in path.rglob("transcript.log")))
            continue
        raise ValueError(f"Transcript cleanup target does not exist: {path}")
    unique_paths = tuple(dict.fromkeys(transcript_paths))
    if not unique_paths:
        raise ValueError("Transcript cleanup did not find any transcript files.")
    return unique_paths


if __name__ == "__main__":
    raise SystemExit(main())
