"""Supported Puzzles & Conquest screen states."""

from enum import StrEnum


class ScreenType(StrEnum):
    """Known Android and P&C screens relevant to automation decisions."""

    UNKNOWN = "unknown"
    ANDROID_HOME = "android_home"
    PNC_LOADING = "pnc_loading"
    PNC_LOGIN = "pnc_login"
    PNC_ACCOUNT_SWITCH = "pnc_account_switch"
    PNC_CASTLE_SELECTION = "pnc_castle_selection"
    PNC_HOME_CITY = "pnc_home_city"
    PNC_MORE_MENU = "pnc_more_menu"
    PNC_LORD_INFO = "pnc_lord_info"
    PNC_PLAYER_TERRITORY = "pnc_player_territory"
    PNC_PLAYER_PROFILE = "pnc_player_profile"
    PNC_VIP = "pnc_vip"
    PNC_IMPROVE_MIGHT = "pnc_improve_might"
    PNC_BAG = "pnc_bag"
    PNC_QUEST_DAILY = "pnc_quest_daily"
    PNC_HERO_LIST = "pnc_hero_list"
    PNC_HERO_DETAIL_UPGRADE = "pnc_hero_detail_upgrade"
    PNC_HERO_DETAIL_ENHANCE = "pnc_hero_detail_enhance"
    PNC_MAIL_HUB = "pnc_mail_hub"
    PNC_MAILBOX_LIST = "pnc_mailbox_list"
    PNC_MAIL_THREAD = "pnc_mail_thread"
    PNC_MAIL_COMPOSE_POPUP = "pnc_mail_compose_popup"
    PNC_ALLIANCE_HOME = "pnc_alliance_home"
    PNC_ALLIANCE_JOIN = "pnc_alliance_join"
    PNC_ALLIANCE_MEMBER_LIST = "pnc_alliance_member_list"
    PNC_ALLIANCE_MEMBER_MANAGE_POPUP = "pnc_alliance_member_manage_popup"
    PNC_CHAT = "pnc_chat"
    PNC_CHAT_PLAYER_ACTION_POPUP = "pnc_chat_player_action_popup"
    PNC_CASH_MALL = "pnc_cash_mall"
    PNC_DAILY_TO_DO = "pnc_daily_to_do"
    PNC_GIFT_CENTER = "pnc_gift_center"
    PNC_EVENT_CENTER = "pnc_event_center"
    PNC_BUILDING_DETAILS = "pnc_building_details"
    PNC_ACADEMY = "pnc_academy"
    PNC_RESEARCH_TREE = "pnc_research_tree"
    PNC_WORLD_MAP = "pnc_world_map"
    PNC_GATHER_NODE = "pnc_gather_node"
    PNC_MARCH_CONFIRM = "pnc_march_confirm"
    PNC_MIGHT_RANK = "pnc_might_rank"
    PNC_CAMPAIGN = "pnc_campaign"
    PNC_CAMPAIGN_STAGE = "pnc_campaign_stage"
    PNC_BATTLE_PREP = "pnc_battle_prep"
    PNC_POPUP = "pnc_popup"
